### PR TITLE
more complete stageapi defs

### PR DESCRIPTION
**Pull request by KyojoH**
why did they document this so poorly this is hell

### CODE REVIEW

**Comment by Zamiell** [comment]
lets not use all caps, this is a civil repository

**Comment by Zamiell** [comment]
also this fails the linter, make sure your shit passes the linter before you submit a pull request

**Comment by Zamiell** [comment]
no comments should be shouting

**Comment by KyojoH** [comment]
the comment in all caps is directly from the stageapi docs. also it's not the only one in all caps. so i assumed it was fine

**Comment by Zamiell** [comment]
fine

**Pull request merged**
